import { buildOperations, renderOperations, renderSchemas } from './build';
import type { OpenApiDoc } from './openapi.types';

const DOC: OpenApiDoc = {
  openapi: '3.0.0',
  info: { title: 'Cybernetics', version: '1.0' },
  paths: {
    '/contacts': {
      get: {
        operationId: 'ContactController_list',
        parameters: [
          { name: 'status', in: 'query', schema: { type: 'string' } },
          { name: 'page', in: 'query', schema: { type: 'number' } },
        ],
      },
      post: {
        operationId: 'ContactController_create',
        requestBody: {
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/CreateContactDto' },
            },
          },
        },
      },
    },
    '/contacts/{id}': {
      patch: {
        operationId: 'ContactController_update',
        parameters: [{ name: 'id', in: 'path', schema: { type: 'string' } }],
        requestBody: {
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/UpdateContactDto' },
            },
          },
        },
      },
    },
    '/auth/login': {
      post: { operationId: 'AuthController_login', security: [] },
    },
  },
  components: {
    schemas: {
      CreateContactDto: { type: 'object', properties: { firstName: { type: 'string' } } },
      UpdateContactDto: { type: 'object', properties: { firstName: { type: 'string' } } },
    },
  },
};

describe('buildOperations', () => {
  const ops = buildOperations(DOC);
  const byId = (id: string) => ops.find((o) => o.operationId === id)!;

  it('finds every operation', () => {
    expect(ops.map((o) => o.operationId).sort()).toEqual([
      'AuthController_login',
      'ContactController_create',
      'ContactController_list',
      'ContactController_update',
    ]);
  });

  it('records method and path', () => {
    expect(byId('ContactController_list')).toMatchObject({
      method: 'get',
      path: '/contacts',
    });
  });

  it('separates path params from query params', () => {
    expect(byId('ContactController_list').queryParams).toEqual(['status', 'page']);
    expect(byId('ContactController_list').pathParams).toEqual([]);
    expect(byId('ContactController_update').pathParams).toEqual(['id']);
  });

  it('resolves the request body schema to a component name', () => {
    expect(byId('ContactController_create').requestSchema).toBe('CreateContactDto');
    expect(byId('ContactController_list').requestSchema).toBeUndefined();
  });

  it('marks operations with an empty security array as public', () => {
    expect(byId('AuthController_login').isPublic).toBe(true);
    expect(byId('ContactController_list').isPublic).toBe(false);
  });
});

describe('renderOperations', () => {
  it('emits a compiling module keyed by operationId', () => {
    const out = renderOperations(buildOperations(DOC));
    expect(out).toContain('// GENERATED BY `pnpm codegen` — DO NOT EDIT');
    expect(out).toContain("'ContactController_list':");
    expect(out).toContain('"path":"/contacts"');
    expect(out).toContain('export const operations');
  });

  it('sorts keys so regeneration is diff-stable', () => {
    const out = renderOperations(buildOperations(DOC));
    const order = [...out.matchAll(/^ {2}'([A-Za-z_]+)':/gm)].map((m) => m[1]);
    expect(order).toEqual([...order].sort());
  });
});

describe('renderSchemas', () => {
  it('emits the component schemas verbatim', () => {
    const out = renderSchemas(DOC);
    expect(out).toContain('export const schemas');
    expect(out).toContain('CreateContactDto');
    expect(out).toContain('firstName');
  });

  it('emits an empty object when the document has no components', () => {
    const out = renderSchemas({ ...DOC, components: undefined });
    expect(out).toContain('schemas: Record<string, unknown> = {};');
  });
});
