import {
  HTTP_METHODS,
  type OpenApiDoc,
  type OpenApiOperation,
} from './openapi.types';

export interface OperationMeta {
  operationId: string;
  method: string;
  path: string;
  pathParams: string[];
  queryParams: string[];
  /** Component name of the JSON request body schema, if the operation takes one. */
  requestSchema?: string;
  isPublic: boolean;
}

const BANNER = '// GENERATED BY `pnpm codegen` — DO NOT EDIT\n';

function requestSchemaOf(op: OpenApiOperation): string | undefined {
  const ref = op.requestBody?.content?.['application/json']?.schema?.$ref;
  if (!ref) return undefined;
  return ref.split('/').pop();
}

export function buildOperations(doc: OpenApiDoc): OperationMeta[] {
  const out: OperationMeta[] = [];
  for (const [path, item] of Object.entries(doc.paths ?? {})) {
    for (const method of HTTP_METHODS) {
      const op = item?.[method];
      if (!op?.operationId) continue;
      const params = op.parameters ?? [];
      out.push({
        operationId: op.operationId,
        method,
        path,
        pathParams: params.filter((p) => p.in === 'path').map((p) => p.name),
        queryParams: params.filter((p) => p.in === 'query').map((p) => p.name),
        requestSchema: requestSchemaOf(op),
        // `stripSecurityForPublic` in the API sets `security: []` on @Public()
        // routes; that empty array is the only public marker in the document.
        isPublic: Array.isArray(op.security) && op.security.length === 0,
      });
    }
  }
  return out;
}

export function renderOperations(ops: OperationMeta[]): string {
  // Sorted so `pnpm codegen` produces a stable diff and the CI drift check
  // reports real changes rather than key reordering.
  const sorted = [...ops].sort((a, b) =>
    a.operationId.localeCompare(b.operationId),
  );
  const body = sorted
    .map((op) => `  '${op.operationId}': ${JSON.stringify(op)},`)
    .join('\n');

  return `${BANNER}
export interface OperationMeta {
  operationId: string;
  method: string;
  path: string;
  pathParams: string[];
  queryParams: string[];
  requestSchema?: string;
  isPublic: boolean;
}

export const operations: Record<string, OperationMeta> = {
${body}
};
`;
}

export function renderSchemas(doc: OpenApiDoc): string {
  const schemas = doc.components?.schemas;
  const rendered =
    schemas && Object.keys(schemas).length > 0
      ? JSON.stringify(sortKeys(schemas), null, 2)
      : '{}';
  return `${BANNER}
export const schemas: Record<string, unknown> = ${rendered};
`;
}

function sortKeys<T extends Record<string, unknown>>(obj: T): T {
  return Object.fromEntries(
    Object.keys(obj)
      .sort()
      .map((k) => [k, obj[k]]),
  ) as T;
}
